# Generated by Django 2.1.7 on 2019-06-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaries',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
    ]
