# Generated by Django 2.1.7 on 2019-06-19 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190619_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='note',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
