# Generated by Django 2.1.7 on 2019-06-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
